import os

SECRET_KEY = os.getenv('SURVEYPRO_SECRET_KEY', 'SUPER_SECRET_KEY_FOR_SURVEYPRO_PROJECT_2026')
ALGORITHM = os.getenv('SURVEYPRO_JWT_ALGORITHM', 'HS256')
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('SURVEYPRO_ACCESS_TOKEN_EXPIRE_MINUTES', str(24 * 60)))

GOOGLE_CLIENT_ID = os.getenv('SURVEYPRO_GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('SURVEYPRO_GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = os.getenv('SURVEYPRO_GOOGLE_REDIRECT_URI', 'http://localhost:8000/auth/google/callback')
FRONTEND_URL = os.getenv('SURVEYPRO_FRONTEND_URL', 'http://localhost:5173')
